# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    displayName: 'Gradle build, tests, code coverage report'
    inputs:
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'doJacocoOfflineInstrumentation buildCrowdinCliJar test jacocoTestReport'
  - bash: |
      bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
    displayName: 'Upload coverage to codecov.io'
